language: php
php:
  - "5.4"
  - "5.3"
before_script:
  - composer install --dev
  - mysql -e 'create database stefano-tests;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('test') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
after_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script: phpunit --configuration ./tests/configuration.xml