<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'StefanoDb\Lock'                               => __DIR__ . '/src/StefanoDb/Lock.php',
    'StefanoDb\LockStrategy\LockStrategyInterface' => __DIR__ . '/src/StefanoDb/LockStrategy/LockStrategyInterface.php',
    'StefanoDb\LockStrategy\Mysql'                 => __DIR__ . '/src/StefanoDb/LockStrategy/Mysql.php',
    'StefanoDb\LockStrategy\Postgresql'            => __DIR__ . '/src/StefanoDb/LockStrategy/Postgresql.php',
    'StefanoDb\Transaction'                        => __DIR__ . '/src/StefanoDb/Transaction.php',
    'StefanoDb\TransactionManager'                 => __DIR__ . '/src/StefanoDb/TransactionManager.php',
);
