<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'StefanoDb\Lock\Adapter\AbstractAdapter'            => __DIR__ . '/src/StefanoDb/Lock/Adapter/AbstractAdapter.php',
    'StefanoDb\Lock\Adapter\Mysql'                      => __DIR__ . '/src/StefanoDb/Lock/Adapter/Mysql.php',
    'StefanoDb\Lock\Adapter\Postgresql'                 => __DIR__ . '/src/StefanoDb/Lock/Adapter/Postgresql.php',
    'StefanoDb\Lock\Exception\InvalidArgumentException' => __DIR__ . '/src/StefanoDb/Lock/Exception/InvalidArgumentException.php',
    'StefanoDb\Lock\LockFactory'                        => __DIR__ . '/src/StefanoDb/Lock/LockFactory.php',
    'StefanoDb\Lock\LockInterface'                      => __DIR__ . '/src/StefanoDb/Lock/LockInterface.php',
    'StefanoDb\Transaction\Transaction'                 => __DIR__ . '/src/StefanoDb/Transaction/Transaction.php',
    'StefanoDb\Transaction\TransactionInterface'        => __DIR__ . '/src/StefanoDb/Transaction/TransactionInterface.php',
    'StefanoDb\Transaction\TransactionManager'          => __DIR__ . '/src/StefanoDb/Transaction/TransactionManager.php',
    'StefanoDb\Transaction\TransactionManagerInterface' => __DIR__ . '/src/StefanoDb/Transaction/TransactionManagerInterface.php',
);
